kind: Pod
apiVersion: v1
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: myvolume
      persistentVolumeClaim:
       claimName: local-pvc1
  containers:
    - name: task-pv-container
      image: nginx
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: myvolume


# apiVersion: v1
# kind: Pod
# metadata:
#   name: www
#   labels:
#     name: www
# spec:
#   containers:
#   - name: www
#     image: nginx:alpine
#     ports:
#       - containerPort: 80
#         name: www
#     volumeMounts:
#       - name: www-persistent-storage
#         mountPath: /usr/share/nginx/html
#   volumes:
#     - name: www-persistent-storage
#       persistentVolumeClaim:
#         claimName: my-claim