apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc1
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1050Mi

# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: my-claim
# spec:
#   accessModes:
#   - ReadWriteOnce
#   storageClassName: my-local-storage
#   resources:
#     requests:
#       storage: 2Gi